### ISSUE TITLE
Secure vs. non-secure form action

### ISSUE THREAD

**Issue by derfberg** [ActiveCampaign/app-wordpress#3]
Hi,
I have an embedded Active Campaign form in the footer of my site using the shortcode through this plug-in. But when the site goes into secure mode during checkout - the form action is still using non-secure mode which triggers the mixed-security content warning from the browsers. Is there an easy fix for this? I'm guessing the action url gets pulled in via the api as non-secure and is never converted to the neutral url (i.e. action="//mysite,activehost.com/proc.php") which would work in both secure and non-secure modes.

Thanks,

Fred

**Comment by mthommes** [comment]
Hi Fred,

Thanks for mentioning this. I have verified this issue and we will have an update in place very soon to correct this. I'll post here once the updated plugin is ready.

**Comment by derfberg** [comment]
Fantastic - thanks for your help!

**Comment by mthommes** [comment]
Hi - this should be fixed now. I've pushed an update that removes the protocol so it shouldn't cause security warnings. You may have to uninstall then re-install the plugin on your WordPress site, and click "Update" again for the ActiveCampaign settings.

Let us know if you still experience this issue.

Thanks!

**Comment by derfberg** [comment]
Works beautifully - thank you!
