### ISSUE TITLE
Subscribe user on woocommerce checkout page using custom checkbox

### ISSUE THREAD

**Issue by VivekShingala** [ActiveCampaign/app-wordpress#47]
Hi Team

I am using active campaign on my WordPress website and I want to provide an option (a custom checkbox) on the checkout page to subscribe my customer directly to active campaign. Please advise on how to achieve this? Moreover, after subscribing the user from woocommerce checkout page, can we highlight or show flag under ActiveCampaign subscribers list to mention that the customer was subscribed through the custom checkbox on the checkout page?

Thanks.

**Comment by bartboy011** [comment]
@VivekShingala Thanks for reaching out - are you using WooCommerce? If so, we have a plugin coming soon that will handle all of that for you!

**Comment by VivekShingala** [comment]
Hi @bartboy011 , yes, we are using WooCommerce.

Could you please let me know when you are planning to launch the plugin? Also, it would be great if you can provide some article or URL to subscribe the users manually to ActiveCampaign if possible thanks.

**Comment by bartboy011** [comment]
@VivekShingala The official release date is not-yet-determined, but I'll update you once it's decided. 

Please take a look at our [PHP API Wrapper](https://github.com/ActiveCampaign/activecampaign-api-php). Here's a brief example of subscribing a contact:

```php
$ac = new ActiveCampaign('apiurl', 'apikey');

$contact = array(
	"email"              => "test@example.com",
	"first_name"         => "Test",
	"last_name"          => "Test",
	"p[{$list_id}]"      => $list_id,
	"status[{$list_id}]" => 1, // "Active" status
);

$contact_sync = $ac->api("contact/sync", $contact);
```

**Comment by VivekShingala** [comment]
Thank you so much for your quick response @bartboy011. I will implement this solution to subscribe my users.

**Comment by bartboy011** [comment]
@VivekShingala of course!
